export const LANDING = '/'
// export const SIGN_UP = '/signup'
export const LOGIN = '/login'
export const DASHBOARD = '/dashboard'
export const PROJECTOR = '/projector'
// export const ADMIN = '/admin'
// export const PASSWORD_FORGET = '/pw-forget'